openapi: 3.0.3
info:
  title: LWN Simulator API
  version: 1.0.0
  description: API contract for LWN Simulator
paths: {}
components:
  schemas:
    AppInfoResponse:
      title: AppInfoResponse
      type: object
      properties:
        app:
          type: string
        version:
          type: string
      required:
        - app
        - version
    StatusResponse:
      title: StatusResponse
      type: object
      properties:
        port:
          type: string
      required:
        - port
    DeviceClass:
      title: DeviceClass
      type: string
      enum:
        - class-a
        - class-b
        - class-c
      x-enum-varnames:
        - ClassA
        - ClassB
        - ClassC
    DeviceActivation:
      title: DeviceClass
      type: string
      enum:
        - oota
        - abp
      x-enum-varnames:
        - OOTA
        - ABP
    OOTAConfig:
      title: OOTAConfig
      type: object
      properties:
        joinEUI:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=16
        appKey:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=32
      required:
        - joinEUI
        - appKey
    ABPConfig:
      title: ABPConfig
      type: object
      properties:
        devAddr:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=8
        nwkSKey:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=32
        appSKey:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=32
      required:
        - devAddr
        - nwkSKey
        - appSKey
    DeviceRegion:
      title: DeviceClass
      type: string
      enum:
        - EU868
        - US915
        - CN779
        - EU433
        - AU915
        - CN470
        - AS923
        - KR920
        - IN865
        - RU864
      x-enum-varnames:
        - EU868
        - US915
        - CN779
        - EU433
        - AU915
        - CN470
        - AS923
        - KR920
        - IN865
        - RU864
    LocationConfig:
      title: LocationConfig
      type: object
      properties:
        latitude:
          type: number
          x-go-type: '*float32'
          x-oapi-codegen-extra-tags:
            validate: required,min=-90,max=90
        longitude:
          type: number
          x-go-type: '*float32'
          x-oapi-codegen-extra-tags:
            validate: required,min=-180,max=180
        altitude:
          type: number
          x-go-type: '*float32'
          x-oapi-codegen-extra-tags:
            validate: required
        region:
          $ref: '#/components/schemas/DeviceRegion'
      required:
        - latitude
        - longitude
        - altitude
        - region
    FrameConfig:
      title: FrameConfig
      type: object
      properties:
        fPort:
          type: integer
          x-oapi-codegen-extra-tags:
            validate: required,min=1,max=223
        retransmission:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        FCntUp:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        FCntDown:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        disableFrameCounterValidation:
          type: boolean
      required:
        - fPort
        - retransmission
        - disableFrameCounterValidation
    OversizedPayloadBehavior:
      title: DeviceClass
      type: string
      enum:
        - fragment
        - truncate
      x-enum-varnames:
        - Fragment
        - Truncate
    DeviceMType:
      title: DeviceClass
      type: string
      enum:
        - confirmed-data-up
        - unconfirmed-data-up
      x-enum-varnames:
        - ConfirmedDataUp
        - UnconfirmedDataUp
    PayloadConfig:
      title: PayloadConfig
      type: object
      properties:
        uplinkInterval:
          type: number
          x-oapi-codegen-extra-tags:
            validate: required,gt=0
        oversizedPayloadBehavior:
          $ref: '#/components/schemas/OversizedPayloadBehavior'
        MType:
          $ref: '#/components/schemas/DeviceMType'
        payload:
          type: string
        base64Encoded:
          type: boolean
      required:
        - uplinkInterval
        - oversizedPayloadBehavior
        - MType
        - payload
        - base64Encoded
    AdvancedConfig:
      title: AdvancedConfig
      type: object
      properties:
        antennaRange:
          type: number
          x-oapi-codegen-extra-tags:
            validate: required,gt=0
        ADREnabled:
          type: boolean
      required:
        - antennaRange
        - ADREnabled
    Device:
      title: Device
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            validate: required,len=36
        active:
          type: boolean
        name:
          type: string
        devEUI:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=16
        class:
          $ref: '#/components/schemas/DeviceClass'
        RX1Config:
          $ref: '#/components/schemas/RX1Config'
        RX2Config:
          $ref: '#/components/schemas/RX2Config'
        activation:
          $ref: '#/components/schemas/DeviceActivation'
        OOTAConfig:
          $ref: '#/components/schemas/OOTAConfig'
        ABPConfig:
          $ref: '#/components/schemas/ABPConfig'
        locationConfig:
          $ref: '#/components/schemas/LocationConfig'
        frameConfig:
          $ref: '#/components/schemas/FrameConfig'
        payloadConfig:
          $ref: '#/components/schemas/PayloadConfig'
        advancedConfig:
          $ref: '#/components/schemas/AdvancedConfig'
      required:
        - id
        - active
        - name
        - devEUI
        - class
        - RX1Config
        - RX2Config
        - activation
        - locationConfig
        - frameConfig
        - payloadConfig
        - advancedConfig
    CreateDeviceRequest:
      title: CreateDeviceRequest
      type: object
      properties:
        devEUI:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=16
        name:
          type: string
        activation:
          $ref: '#/components/schemas/DeviceActivation'
        class:
          $ref: '#/components/schemas/DeviceClass'
        locationConfig:
          $ref: '#/components/schemas/LocationConfig'
        ABPConfig:
          $ref: '#/components/schemas/ABPConfig'
        OOTAConfig:
          $ref: '#/components/schemas/OOTAConfig'
        RX1Config:
          $ref: '#/components/schemas/RX1Config'
        RX2Config:
          $ref: '#/components/schemas/RX2Config'
        advancedConfig:
          $ref: '#/components/schemas/AdvancedConfig'
        frameConfig:
          $ref: '#/components/schemas/FrameConfig'
        payloadConfig:
          $ref: '#/components/schemas/PayloadConfig'
      required:
        - devEUI
        - name
        - active
        - activation
        - class
        - locationConfig
        - RX1Config
        - RX2Config
        - advancedConfig
        - frameConfig
        - payloadConfig
    CreateDeviceResponse:
      title: CreateDeviceResponse
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
      required:
        - device
    GetDeviceRequest:
      title: GetDeviceRequest
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
          x-go-json-ignore: true
          x-oapi-codegen-extra-tags:
            validate: required,len=36
            uri: id
      required:
        - id
    GetDeviceResponse:
      title: GetDeviceResponse
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
      required:
        - device
    GetDevicesRequest:
      title: GetDevicesRequest
      type: object
      x-go-type: struct{}
      additionalProperties: false
      properties: {}
    GetDevicesResponse:
      title: GetDeviceResponse
      type: object
      properties:
        devices:
          type: array
          items:
            $ref: '#/components/schemas/Device'
      required:
        - devices
    UpdateDeviceRequest:
      title: UpdateDeviceRequest
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
          x-go-json-ignore: true
          x-oapi-codegen-extra-tags:
            validate: required,len=36
            uri: id
        device:
          $ref: '#/components/schemas/Device'
      required:
        - id
        - device
    UpdateDeviceResponse:
      title: UpdateDeviceResponse
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
      required:
        - device
    DeleteDeviceRequest:
      title: GetDeviceRequest
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
          x-go-json-ignore: true
          x-oapi-codegen-extra-tags:
            validate: required,len=36
            uri: id
      required:
        - id
    DeleteDeviceResponse:
      title: GetDevicesResponse
      type: object
      x-go-type: struct{}
      additionalProperties: false
      properties: {}
    Gateway:
      title: Gateway
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        gatewayEUI:
          type: string
        latitude:
          type: number
        longitude:
          type: number
      required:
        - id
        - gatewayEUI
        - latitude
        - longitude
    CreateGatewayRequest:
      title: CreateGatewayRequest
      type: object
      properties:
        gatewayEUI:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required,len=16
        latitude:
          type: number
          x-go-type: '*float32'
          x-oapi-codegen-extra-tags:
            validate: required,min=-90,max=90
        longitude:
          type: number
          x-go-type: '*float32'
          x-oapi-codegen-extra-tags:
            validate: required,min=-180,max=180
      required:
        - gatewayEUI
        - latitude
        - longitude
    CreateGatewayResponse:
      title: CreateGatewayResponse
      type: object
      properties:
        gateway:
          $ref: '#/components/schemas/Gateway'
      required:
        - gateway
    RX1Config:
      title: RX1Config
      type: object
      properties:
        delay:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        duration:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        dataRateOffset:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
      required:
        - delay
        - duration
        - dataRateOffset
    RX2Config:
      title: RX2Config
      type: object
      properties:
        delay:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        duration:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        channelFrequency:
          type: number
          x-oapi-codegen-extra-tags:
            validate: required,gt=0
        dataRate:
          type: integer
          x-go-type: '*int'
          x-oapi-codegen-extra-tags:
            validate: required,min=0
        ACKTimeout:
          type: integer
          x-oapi-codegen-extra-tags:
            validate: required,min=1000,max=3000
      required:
        - delay
        - duration
        - channelFrequency
        - dataRate
        - ACKTimeout
