openapi: 3.0.3

info:
  title: LWN Simulator API
  version: 1.0.0
  description: API contract for LWN Simulator

paths: {}

components:
  schemas:
    AppInfoResponse:
      $ref: "./schemas/AppInfoResponse.yaml"
    StatusResponse:
      $ref: "./schemas/StatusResponse.yaml"
    Device:
      $ref: "./schemas/Device/Device.yaml"
    CreateDeviceRequest:
      $ref: "./schemas/Device/CreateDeviceRequest.yaml"
    CreateDeviceResponse:
      $ref: "./schemas/Device/CreateDeviceResponse.yaml"
    Gateway:
      $ref: "./schemas/Gateway/Gateway.yaml"
