openapi: 3.0.3

info:
  title: LWN Simulator API
  version: 1.0.0
  description: API contract for LWN Simulator

paths: {}

components:
  schemas:
    AppInfoResponse:
      $ref: "./schemas/AppInfoResponse.yaml"
    StatusResponse:
      $ref: "./schemas/StatusResponse.yaml"
    DeviceClass:
      $ref: "./schemas/Device/DeviceProps/DeviceClass.yaml"
    DeviceActivation:
      $ref: "./schemas/Device/DeviceProps/DeviceActivation.yaml"
    OOTAConfig:
      $ref: "./schemas/Device/DeviceProps/OOTAConfig.yaml"
    ABPConfig:
      $ref: "./schemas/Device/DeviceProps/ABPConfig.yaml"
    DeviceRegion:
      $ref: "./schemas/Device/DeviceProps/DeviceRegion.yaml"
    LocationConfig:
      $ref: "./schemas/Device/DeviceProps/LocationConfig.yaml"
    FrameConfig:
      $ref: "./schemas/Device/DeviceProps/FrameConfig.yaml"
    OversizedPayloadBehavior:
      $ref: "./schemas/Device/DeviceProps/OversizedPayloadBehavior.yaml"
    DeviceMType:
      $ref: "./schemas/Device/DeviceProps/DeviceMType.yaml"
    PayloadConfig:
      $ref: "./schemas/Device/DeviceProps/PayloadConfig.yaml"
    AdvancedConfig:
      $ref: "./schemas/Device/DeviceProps/AdvancedConfig.yaml"
    Device:
      $ref: "./schemas/Device/Device.yaml"
    CreateDeviceRequest:
      $ref: "./schemas/Device/CreateDeviceRequest.yaml"
    CreateDeviceResponse:
      $ref: "./schemas/Device/CreateDeviceResponse.yaml"
    GetDeviceRequest:
      $ref: "./schemas/Device/GetDeviceRequest.yaml"
    GetDeviceResponse:
      $ref: "./schemas/Device/GetDeviceResponse.yaml"
    GetDevicesRequest:
      $ref: "./schemas/Device/GetDevicesRequest.yaml"
    GetDevicesResponse:
      $ref: "./schemas/Device/GetDevicesResponse.yaml"
    UpdateDeviceRequest:
      $ref: "./schemas/Device/UpdateDeviceRequest.yaml"
    UpdateDeviceResponse:
      $ref: "./schemas/Device/UpdateDeviceResponse.yaml"
    DeleteDeviceRequest:
      $ref: "./schemas/Device/DeleteDeviceRequest.yaml"
    DeleteDeviceResponse:
      $ref: "./schemas/Device/DeleteDeviceResponse.yaml"
    Gateway:
      $ref: "./schemas/Gateway/Gateway.yaml"
    CreateGatewayRequest:
      $ref: "./schemas/Gateway/CreateGatewayRequest.yaml"
    CreateGatewayResponse:
      $ref: "./schemas/Gateway/CreateGatewayResponse.yaml"
