title: OOTAConfig
type: object

properties:
  joinEUI:
    type: string
    x-oapi-codegen-extra-tags:
      validate: "required,len=16"
  appKey:
    type: string
    x-oapi-codegen-extra-tags:
      validate: "required,len=32"

required:
  - joinEUI
  - appKey
