title: RX1Config
type: object

properties:
  delay:
    type: integer
    x-oapi-codegen-extra-tags:
      validate: "required,min=0"
  duration:
    type: integer
    x-oapi-codegen-extra-tags:
      validate: "required,min=0"
  dataRateOffset:
    type: integer
    x-oapi-codegen-extra-tags:
      validate: "required,min=0"

required:
  - delay
  - duration
  - dataRateOffset
